<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>MQTTnet.Rx.OmronPlc.Reactive</PackageId>
    <DefineConstants>$(DefineConstants);REACTIVE_SHIM</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="IoT-Driver.OmronPlcRx.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Async.Reactive" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MQTTnet.Rx.Client.Reactive\MQTTnet.Rx.Client.Reactive.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\MQTTnet.Rx.OmronPlc\**\*.cs" Exclude="..\MQTTnet.Rx.OmronPlc\ProjectGlobalUsings.cs;..\MQTTnet.Rx.OmronPlc\bin\**\*.cs;..\MQTTnet.Rx.OmronPlc\obj\**\*.cs" Link="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
