<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);REACTIVE_SHIM</DefineConstants>
    <PackageId>MQTTnet.Rx.Modbus.Reactive</PackageId>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IoT-Driver.ModbusRx.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Async.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MQTTnet.Rx.Client.Reactive\MQTTnet.Rx.Client.Reactive.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="IoT.Driver.ModbusRx.Reactive" />
    <Using Include="IoT.Driver.ModbusRx.Reactive.Device" />
    <Using Include="MQTTnet.Rx.Client.Reactive" />
    <Using Include="ReactiveUI.Primitives.Advanced" />
    <Using Include="ReactiveUI.Primitives.Async" />
    <Using Include="ReactiveUI.Primitives.Disposables" />
    <Using Include="ReactiveUI.Primitives.Reactive" />
    <Using Include="ReactiveUI.Primitives.Reactive.Signals" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\MQTTnet.Rx.Modbus\**\*.cs"
             Exclude="..\MQTTnet.Rx.Modbus\bin\**;..\MQTTnet.Rx.Modbus\obj\**"
             Link="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
