<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MQTTnet.Rx.Client.Reactive</RootNamespace>
    <DefineConstants>$(DefineConstants);REACTIVE_SHIM</DefineConstants>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\MQTTnet.Rx.Client\**\*.cs"
             Exclude="..\MQTTnet.Rx.Client\bin\**;..\MQTTnet.Rx.Client\obj\**"
             Link="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="ReactiveUI.Primitives.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Async.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ReactiveUI.Primitives.Reactive" />
    <Using Include="System.Reactive.Concurrency.IScheduler" Alias="ISequencer" />
    <Using Include="System.Reactive.Concurrency.IScheduler" Alias="IScheduler" />
    <Using Include="System.Reactive.Unit" Alias="RxUnit" />
    <Using Include="System.Reactive.Unit" Alias="RxVoid" />
  </ItemGroup>
</Project>
