<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet.Extensions.TopicTemplate" />
    <PackageReference Include="ReactiveUI.Primitives" />
    <PackageReference Include="ReactiveUI.Primitives.Async" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ReactiveUI.Primitives" />
    <Using Include="ReactiveUI.Primitives.Async" />
    <Using Include="ReactiveUI.Primitives.Async.Disposables" />
    <Using Include="ReactiveUI.Primitives.Signals" />
  </ItemGroup>

</Project>
