<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IoT-Driver.ModbusRx" />
    <PackageReference Include="ReactiveUI.Primitives.Async.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MQTTnet.Rx.Client\MQTTnet.Rx.Client.csproj" />
  </ItemGroup>

</Project>
