<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>MQTTnet.Rx.OmronPlc</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IoT-Driver.OmronPlcRx" />
    <PackageReference Include="ReactiveUI.Primitives" />
    <PackageReference Include="ReactiveUI.Primitives.Async" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MQTTnet.Rx.Client\MQTTnet.Rx.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="IoT.Driver.Core" />
    <Using Include="IoT.Driver.OmronPlcRx" />
    <Using Include="MQTTnet.Rx.Client" />
    <Using Include="ReactiveUI.Primitives" />
    <Using Include="ReactiveUI.Primitives.Async" />
    <Using Include="MQTTnet.Rx.Client.ObservableBridgeCompatibilityExtensions" Alias="ObservableSignalConversion" />
  </ItemGroup>

</Project>
