<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);REACTIVE_SHIM</DefineConstants>
    <PackageId>MQTTnet.Rx.Server.Reactive</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet.Server" />
    <PackageReference Include="ReactiveUI.Primitives.Async.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ReactiveUI.Primitives.Async" />
    <Using Include="ReactiveUI.Primitives.Async.Disposables" />
    <Using Include="ReactiveUI.Primitives.Disposables" />
    <Using Include="ReactiveUI.Primitives.Reactive" />
    <Using Include="ReactiveUI.Primitives.Reactive.Signals" />
    <Using Include="ReactiveUI.Primitives.Reactive.Signals.Signal" Alias="SignalFactory" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\MQTTnet.Rx.Server\*.cs" Link="%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
