<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);REACTIVE_SHIM</DefineConstants>
    <PackageId>MQTTnet.SerialPort.Reactive</PackageId>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\MQTTnet.Rx.SerialPort\**\*.cs"
             Exclude="..\MQTTnet.Rx.SerialPort\bin\**;..\MQTTnet.Rx.SerialPort\obj\**"
             Link="%(RecursiveDir)%(Filename)%(Extension)" />
    <PackageReference Include="IoT-Driver.SerialPortRx.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Async.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MQTTnet.Rx.Client.Reactive\MQTTnet.Rx.Client.Reactive.csproj" />
  </ItemGroup>

</Project>
