<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows10.0.19041;net9.0-windows10.0.19041;net10.0-windows10.0.19041;net11.0-windows10.0.19041</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);REACTIVE_SHIM</DefineConstants>
    <PackageId>MQTTnet.TwinCATRx.Reactive</PackageId>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IoT-Driver.TwinCATRx.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Async.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MQTTnet.Rx.Client.Reactive\MQTTnet.Rx.Client.Reactive.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="CP.Collections.Reactive" />
    <Using Include="IoT.Driver.TwinCATRx.Reactive" />
    <Using Include="MQTTnet.Rx.Client.Reactive" />
    <Using Include="ReactiveUI.Primitives.Advanced" />
    <Using Include="ReactiveUI.Primitives.Async" />
    <Using Include="ReactiveUI.Primitives.Reactive" />
    <Using Include="CP.Collections.Reactive.HashTableRx" Alias="IHashTableRx" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\MQTTnet.Rx.TwinCAT\**\*.cs"
             Exclude="..\MQTTnet.Rx.TwinCAT\bin\**;..\MQTTnet.Rx.TwinCAT\obj\**"
             Link="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
