<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**;obj\**" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="ReactiveUI.Primitives" />
    <PackageReference Include="ReactiveUI.Primitives.Async" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ReactiveUI.Primitives" />
    <Using Include="ReactiveUI.Primitives.Concurrency.ISequencer" Alias="ISequencer" />
    <Using Include="ReactiveUI.Primitives.Concurrency.ISequencer" Alias="IScheduler" />
    <Using Include="ReactiveUI.Primitives.RxVoid" Alias="RxUnit" />
    <Using Include="ReactiveUI.Primitives.RxVoid" Alias="RxVoid" />
  </ItemGroup>
</Project>
