<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MQTTnet.Rx.Extensions.TopicTemplate.Reactive</RootNamespace>
    <DefineConstants>$(DefineConstants);REACTIVE_SHIM</DefineConstants>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet.Extensions.TopicTemplate" />
    <PackageReference Include="ReactiveUI.Primitives.Reactive" />
    <PackageReference Include="ReactiveUI.Primitives.Async.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\MQTTnet.Rx.Extensions.TopicTemplate\**\*.cs"
             Exclude="..\MQTTnet.Rx.Extensions.TopicTemplate\bin\**;..\MQTTnet.Rx.Extensions.TopicTemplate\obj\**"
             Link="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ReactiveUI.Primitives.Async" />
    <Using Include="ReactiveUI.Primitives.Async.Disposables" />
    <Using Include="ReactiveUI.Primitives.Reactive" />
    <Using Include="ReactiveUI.Primitives.Reactive.Signals" />
  </ItemGroup>

</Project>
