<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>MQTTnet.SerialPort</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IoT-Driver.SerialPortRx" />
    <PackageReference Include="ReactiveUI.Primitives.Async" />
    <PackageReference Include="ReactiveUI.Primitives" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MQTTnet.Rx.Client\MQTTnet.Rx.Client.csproj" />
  </ItemGroup>

</Project>
