<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MQTTnetRxTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IoT-Driver.SerialPortRx" />
    <PackageReference Include="ReactiveUI.Primitives.Async" />
    <PackageReference Include="ReactiveUI.Primitives" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MQTTnet.Rx.Client\MQTTnet.Rx.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="IoT.Driver.Serial" />
    <Using Include="MQTTnet.Rx.Client" />
    <Using Include="ReactiveUI.Primitives" />
    <Using Include="ReactiveUI.Primitives.Advanced" />
    <Using Include="ReactiveUI.Primitives.Async" />
  </ItemGroup>

</Project>
